services:
  - type: web
    name: convertube-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        sync: false
